<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/engine/value.proto

namespace GPBMetadata\Sajari\Engine;

class Value
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab6010a1973616a6172692f656e67696e652f76616c75652e70726f746f" .
            "120d73616a6172692e656e67696e652281010a0556616c7565120e0a046e" .
            "756c6c180120012808480012100a0673696e676c65180220012809480012" .
            "310a08726570656174656418032001280b321d2e73616a6172692e656e67" .
            "696e652e56616c75652e526570656174656448001a1a0a08526570656174" .
            "6564120e0a0676616c75657318012003280942070a0576616c7565620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

