<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/autocomplete/autocomplete.proto

namespace Sajari\Autocomplete;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * TrainQueryRequest is a query used to train the autocomplete
 * model what is popular from a user perspective.
 * </pre>
 *
 * Protobuf type <code>sajari.autocomplete.TrainQueryRequest</code>
 */
class TrainQueryRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Model to train.
     * </pre>
     *
     * <code>.sajari.autocomplete.Model model = 1;</code>
     */
    private $model = null;
    /**
     * <pre>
     * The full query phrase.
     * </pre>
     *
     * <code>string phrase = 2;</code>
     */
    private $phrase = '';
    /**
     * <pre>
     * The query phrase broken into terms. Typically this would use spaces
     * as delimiters, but it is not restricted to spaces for language flexibility.
     * </pre>
     *
     * <code>repeated string terms = 3;</code>
     */
    private $terms;

    public function __construct() {
        \GPBMetadata\Sajari\Autocomplete\Autocomplete::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Model to train.
     * </pre>
     *
     * <code>.sajari.autocomplete.Model model = 1;</code>
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * <pre>
     * Model to train.
     * </pre>
     *
     * <code>.sajari.autocomplete.Model model = 1;</code>
     */
    public function setModel(&$var)
    {
        GPBUtil::checkMessage($var, \Sajari\Autocomplete\Model::class);
        $this->model = $var;
    }

    /**
     * <pre>
     * The full query phrase.
     * </pre>
     *
     * <code>string phrase = 2;</code>
     */
    public function getPhrase()
    {
        return $this->phrase;
    }

    /**
     * <pre>
     * The full query phrase.
     * </pre>
     *
     * <code>string phrase = 2;</code>
     */
    public function setPhrase($var)
    {
        GPBUtil::checkString($var, True);
        $this->phrase = $var;
    }

    /**
     * <pre>
     * The query phrase broken into terms. Typically this would use spaces
     * as delimiters, but it is not restricted to spaces for language flexibility.
     * </pre>
     *
     * <code>repeated string terms = 3;</code>
     */
    public function getTerms()
    {
        return $this->terms;
    }

    /**
     * <pre>
     * The query phrase broken into terms. Typically this would use spaces
     * as delimiters, but it is not restricted to spaces for language flexibility.
     * </pre>
     *
     * <code>repeated string terms = 3;</code>
     */
    public function setTerms(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->terms = $var;
    }

}

