<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/autocomplete/autocomplete.proto

namespace Sajari\Autocomplete;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * TrainCorpusRequest is used to train the corpus to assist in detecting
 * spelling mistakes.
 * </pre>
 *
 * Protobuf type <code>sajari.autocomplete.TrainCorpusRequest</code>
 */
class TrainCorpusRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Model to train.
     * </pre>
     *
     * <code>.sajari.autocomplete.Model model = 1;</code>
     */
    private $model = null;
    /**
     * <pre>
     * The terms to train the corpus with. These should be correctly
     * spelt to avoid autocorrecting to misspellings.
     * </pre>
     *
     * <code>repeated string terms = 2;</code>
     */
    private $terms;

    public function __construct() {
        \GPBMetadata\Sajari\Autocomplete\Autocomplete::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Model to train.
     * </pre>
     *
     * <code>.sajari.autocomplete.Model model = 1;</code>
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * <pre>
     * Model to train.
     * </pre>
     *
     * <code>.sajari.autocomplete.Model model = 1;</code>
     */
    public function setModel(&$var)
    {
        GPBUtil::checkMessage($var, \Sajari\Autocomplete\Model::class);
        $this->model = $var;
    }

    /**
     * <pre>
     * The terms to train the corpus with. These should be correctly
     * spelt to avoid autocorrecting to misspellings.
     * </pre>
     *
     * <code>repeated string terms = 2;</code>
     */
    public function getTerms()
    {
        return $this->terms;
    }

    /**
     * <pre>
     * The terms to train the corpus with. These should be correctly
     * spelt to avoid autocorrecting to misspellings.
     * </pre>
     *
     * <code>repeated string terms = 2;</code>
     */
    public function setTerms(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->terms = $arr;
    }

}

