<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/rpc/empty.proto

namespace Sajari\Rpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Empty is a message used when there is no value returned
 * from a call.
 * </pre>
 *
 * Protobuf type <code>sajari.rpc.GPBEmpty</code>
 */
class GPBEmpty extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Sajari\Rpc\GPBEmpty::initOnce();
        parent::__construct();
    }

}

