<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/rpc/status.proto

namespace Sajari\Rpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Status response
 *
 * Generated from protobuf message <code>sajari.rpc.Status</code>
 */
class Status extends \Google\Protobuf\Internal\Message
{
    /**
     * Status code related to the message.
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     */
    private $code = 0;
    /**
     * Message
     *
     * Generated from protobuf field <code>string message = 2;</code>
     */
    private $message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $code
     *           Status code related to the message.
     *     @type string $message
     *           Message
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Sajari\Rpc\Status::initOnce();
        parent::__construct($data);
    }

    /**
     * Status code related to the message.
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Status code related to the message.
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Message
     *
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Message
     *
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

}

