<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/engine/schema/schema.proto

namespace Sajari\Engine\Schema;

if (false) {
    /**
     * This class is deprecated. Use Sajari\Engine\Schema\Field\Type instead.
     * @deprecated
     */
    class Field_Type {}
}
class_exists(Field\Type::class);
@trigger_error('Sajari\Engine\Schema\Field_Type is deprecated and will be removed in the next major release. Use Sajari\Engine\Schema\Field\Type instead', E_USER_DEPRECATED);

