<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/engine/schema/schema.proto

namespace Sajari\Engine\Schema;

if (false) {
    /**
     * This class is deprecated. Use Sajari\Engine\Schema\Field\Mode instead.
     * @deprecated
     */
    class Field_Mode {}
}
class_exists(Field\Mode::class);
@trigger_error('Sajari\Engine\Schema\Field_Mode is deprecated and will be removed in the next major release. Use Sajari\Engine\Schema\Field\Mode instead', E_USER_DEPRECATED);

