<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/engine/schema/schema.proto

namespace Sajari\Engine\Schema;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Fields is a list of Fields.
 * </pre>
 *
 * Protobuf type <code>sajari.engine.schema.Fields</code>
 */
class Fields extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .sajari.engine.schema.Field fields = 1;</code>
     */
    private $fields;

    public function __construct() {
        \GPBMetadata\Sajari\Engine\Schema\Schema::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .sajari.engine.schema.Field fields = 1;</code>
     */
    public function getFields()
    {
        return $this->fields;
    }

    /**
     * <code>repeated .sajari.engine.schema.Field fields = 1;</code>
     */
    public function setFields(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sajari\Engine\Schema\Field::class);
        $this->fields = $arr;
    }

}

