<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/engine/schema/schema.proto

namespace Sajari\Engine\Schema;

if (false) {
    /**
     * This class is deprecated. Use Sajari\Engine\Schema\MutateFieldRequest\Mutation instead.
     * @deprecated
     */
    class MutateFieldRequest_Mutation {}
}
class_exists(MutateFieldRequest\Mutation::class);
@trigger_error('Sajari\Engine\Schema\MutateFieldRequest_Mutation is deprecated and will be removed in the next major release. Use Sajari\Engine\Schema\MutateFieldRequest\Mutation instead', E_USER_DEPRECATED);

