<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/api/pipeline/v1/record.proto

namespace Sajari\Api\Pipeline\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * SearchResponse is a response to an Add call.
 *
 * Generated from protobuf message <code>sajari.api.pipeline.v1.AddResponse</code>
 */
class AddResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.sajari.engine.store.record.AddResponse response = 1;</code>
     */
    private $response = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Sajari\Engine\Store\Record\AddResponse $response
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Sajari\Api\Pipeline\V1\Record::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.sajari.engine.store.record.AddResponse response = 1;</code>
     * @return \Sajari\Engine\Store\Record\AddResponse
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.sajari.engine.store.record.AddResponse response = 1;</code>
     * @param \Sajari\Engine\Store\Record\AddResponse $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Sajari\Engine\Store\Record\AddResponse::class);
        $this->response = $var;

        return $this;
    }

}

