<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/api/pipeline/v1/control.proto

namespace Sajari\Api\Pipeline\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Create a record pipeline for injesting data into a collection.
 *
 * Generated from protobuf message <code>sajari.api.pipeline.v1.CreateRecordRequest</code>
 */
class CreateRecordRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Pipeline identifier to create.
     *
     * Generated from protobuf field <code>.sajari.api.pipeline.v1.Pipeline pipeline = 1;</code>
     */
    private $pipeline = null;
    /**
     * List of steps that the pipeline will run.
     *
     * Generated from protobuf field <code>repeated .sajari.api.pipeline.v1.CreateStep pre_steps = 2;</code>
     */
    private $pre_steps;
    /**
     * List of steps that the pipeline will run after the record
     * has been added.
     *
     * Generated from protobuf field <code>repeated .sajari.api.pipeline.v1.CreateStep post_steps = 3;</code>
     */
    private $post_steps;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Sajari\Api\Pipeline\V1\Pipeline $pipeline
     *           Pipeline identifier to create.
     *     @type \Sajari\Api\Pipeline\V1\CreateStep[]|\Google\Protobuf\Internal\RepeatedField $pre_steps
     *           List of steps that the pipeline will run.
     *     @type \Sajari\Api\Pipeline\V1\CreateStep[]|\Google\Protobuf\Internal\RepeatedField $post_steps
     *           List of steps that the pipeline will run after the record
     *           has been added.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Sajari\Api\Pipeline\V1\Control::initOnce();
        parent::__construct($data);
    }

    /**
     * Pipeline identifier to create.
     *
     * Generated from protobuf field <code>.sajari.api.pipeline.v1.Pipeline pipeline = 1;</code>
     * @return \Sajari\Api\Pipeline\V1\Pipeline
     */
    public function getPipeline()
    {
        return $this->pipeline;
    }

    /**
     * Pipeline identifier to create.
     *
     * Generated from protobuf field <code>.sajari.api.pipeline.v1.Pipeline pipeline = 1;</code>
     * @param \Sajari\Api\Pipeline\V1\Pipeline $var
     * @return $this
     */
    public function setPipeline($var)
    {
        GPBUtil::checkMessage($var, \Sajari\Api\Pipeline\V1\Pipeline::class);
        $this->pipeline = $var;

        return $this;
    }

    /**
     * List of steps that the pipeline will run.
     *
     * Generated from protobuf field <code>repeated .sajari.api.pipeline.v1.CreateStep pre_steps = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPreSteps()
    {
        return $this->pre_steps;
    }

    /**
     * List of steps that the pipeline will run.
     *
     * Generated from protobuf field <code>repeated .sajari.api.pipeline.v1.CreateStep pre_steps = 2;</code>
     * @param \Sajari\Api\Pipeline\V1\CreateStep[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPreSteps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sajari\Api\Pipeline\V1\CreateStep::class);
        $this->pre_steps = $arr;

        return $this;
    }

    /**
     * List of steps that the pipeline will run after the record
     * has been added.
     *
     * Generated from protobuf field <code>repeated .sajari.api.pipeline.v1.CreateStep post_steps = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPostSteps()
    {
        return $this->post_steps;
    }

    /**
     * List of steps that the pipeline will run after the record
     * has been added.
     *
     * Generated from protobuf field <code>repeated .sajari.api.pipeline.v1.CreateStep post_steps = 3;</code>
     * @param \Sajari\Api\Pipeline\V1\CreateStep[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPostSteps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sajari\Api\Pipeline\V1\CreateStep::class);
        $this->post_steps = $arr;

        return $this;
    }

}

