<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/api/pipeline/v1/control.proto

namespace Sajari\Api\Pipeline\V1;

if (false) {
    /**
     * This class is deprecated. Use Sajari\Api\Pipeline\V1\GetStepResponse\Parameter instead.
     * @deprecated
     */
    class GetStepResponse_Parameter {}
}
class_exists(GetStepResponse\Parameter::class);
@trigger_error('Sajari\Api\Pipeline\V1\GetStepResponse_Parameter is deprecated and will be removed in the next major release. Use Sajari\Api\Pipeline\V1\GetStepResponse\Parameter instead', E_USER_DEPRECATED);

