<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/api/pipeline/v1/control.proto

namespace Sajari\Api\Pipeline\V1;

if (false) {
    /**
     * This class is deprecated. Use Sajari\Api\Pipeline\V1\ListStepsResponse\Step instead.
     * @deprecated
     */
    class ListStepsResponse_Step {}
}
class_exists(ListStepsResponse\Step::class);
@trigger_error('Sajari\Api\Pipeline\V1\ListStepsResponse_Step is deprecated and will be removed in the next major release. Use Sajari\Api\Pipeline\V1\ListStepsResponse\Step instead', E_USER_DEPRECATED);

