<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/api/pipeline/v1/control.proto

namespace Sajari\Api\Pipeline\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sajari.api.pipeline.v1.ListRecordResponse</code>
 */
class ListRecordResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .sajari.api.pipeline.v1.Pipeline pipelines = 1;</code>
     */
    private $pipelines;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Sajari\Api\Pipeline\V1\Pipeline[]|\Google\Protobuf\Internal\RepeatedField $pipelines
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Sajari\Api\Pipeline\V1\Control::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .sajari.api.pipeline.v1.Pipeline pipelines = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPipelines()
    {
        return $this->pipelines;
    }

    /**
     * Generated from protobuf field <code>repeated .sajari.api.pipeline.v1.Pipeline pipelines = 1;</code>
     * @param \Sajari\Api\Pipeline\V1\Pipeline[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPipelines($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sajari\Api\Pipeline\V1\Pipeline::class);
        $this->pipelines = $arr;

        return $this;
    }

}

