<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/api/pipeline/v1/pipeline.proto

namespace Sajari\Api\Pipeline\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Pipeline is an identifier used to specify a pipeline.
 * </pre>
 *
 * Protobuf type <code>sajari.api.pipeline.v1.Pipeline</code>
 */
class Pipeline extends \Google\Protobuf\Internal\Message
{
    protected $pipeline;

    public function __construct() {
        \GPBMetadata\Sajari\Api\Pipeline\V1\Pipeline::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Name uniquely defines a pipeline.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function getName()
    {
        return $this->readOneof(1);
    }

    /**
     * <pre>
     * Name uniquely defines a pipeline.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(1, $var);
    }

    public function getPipeline()
    {
        return $this->pipeline;
    }

}

