<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/bayes/trainingset/trainingset.proto

namespace Sajari\Bayes\Trainingset;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * UploadResponse contains a unique hash for the uploaded data to prevent
 * duplicate documents distorting the training set probabilities
 * </pre>
 *
 * Protobuf type <code>sajari.bayes.trainingset.UploadResponse</code>
 */
class UploadResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * unique hash for the uploaded data
     * </pre>
     *
     * <code>string hash = 1;</code>
     */
    private $hash = '';

    public function __construct() {
        \GPBMetadata\Sajari\Bayes\Trainingset\Trainingset::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * unique hash for the uploaded data
     * </pre>
     *
     * <code>string hash = 1;</code>
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * <pre>
     * unique hash for the uploaded data
     * </pre>
     *
     * <code>string hash = 1;</code>
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->hash = $var;
    }

}

