<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/engine/query/v1/query.proto

namespace Sajari\Engine\Query\V1;

if (false) {
    /**
     * This class is deprecated. Use Sajari\Engine\Query\V1\Aggregate\Metric instead.
     * @deprecated
     */
    class Aggregate_Metric {}
}
class_exists(Aggregate\Metric::class);
@trigger_error('Sajari\Engine\Query\V1\Aggregate_Metric is deprecated and will be removed in the next major release. Use Sajari\Engine\Query\V1\Aggregate\Metric instead', E_USER_DEPRECATED);

