<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/engine/query/v1/query.proto

namespace Sajari\Engine\Query\V1;

if (false) {
    /**
     * This class is deprecated. Use Sajari\Engine\Query\V1\Aggregate\Date instead.
     * @deprecated
     */
    class Aggregate_Date {}
}
class_exists(Aggregate\Date::class);
@trigger_error('Sajari\Engine\Query\V1\Aggregate_Date is deprecated and will be removed in the next major release. Use Sajari\Engine\Query\V1\Aggregate\Date instead', E_USER_DEPRECATED);

