<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/engine/query/v1/query.proto

namespace Sajari\Engine\Query\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * AnalyseResponse contains the analysis of the record against the query
 * request.
 *
 * Generated from protobuf message <code>sajari.engine.query.v1.AnalyseResponse</code>
 */
class AnalyseResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Terms is the list of intersecting terms between the record and the
     * search query request.
     *
     * Generated from protobuf field <code>repeated .sajari.engine.query.v1.AnalyseResponse.Terms terms = 1;</code>
     */
    private $terms;
    /**
     * Status corresponding to each key in the request.
     *
     * Generated from protobuf field <code>repeated .sajari.rpc.Status status = 2;</code>
     */
    private $status;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Sajari\Engine\Query\V1\AnalyseResponse\Terms[]|\Google\Protobuf\Internal\RepeatedField $terms
     *           Terms is the list of intersecting terms between the record and the
     *           search query request.
     *     @type \Sajari\Rpc\Status[]|\Google\Protobuf\Internal\RepeatedField $status
     *           Status corresponding to each key in the request.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Sajari\Engine\Query\V1\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Terms is the list of intersecting terms between the record and the
     * search query request.
     *
     * Generated from protobuf field <code>repeated .sajari.engine.query.v1.AnalyseResponse.Terms terms = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTerms()
    {
        return $this->terms;
    }

    /**
     * Terms is the list of intersecting terms between the record and the
     * search query request.
     *
     * Generated from protobuf field <code>repeated .sajari.engine.query.v1.AnalyseResponse.Terms terms = 1;</code>
     * @param \Sajari\Engine\Query\V1\AnalyseResponse\Terms[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTerms($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sajari\Engine\Query\V1\AnalyseResponse\Terms::class);
        $this->terms = $arr;

        return $this;
    }

    /**
     * Status corresponding to each key in the request.
     *
     * Generated from protobuf field <code>repeated .sajari.rpc.Status status = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Status corresponding to each key in the request.
     *
     * Generated from protobuf field <code>repeated .sajari.rpc.Status status = 2;</code>
     * @param \Sajari\Rpc\Status[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStatus($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sajari\Rpc\Status::class);
        $this->status = $arr;

        return $this;
    }

}

