<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/engine/query/v1/query.proto

namespace Sajari\Engine\Query\V1;

if (false) {
    /**
     * This class is deprecated. Use Sajari\Engine\Query\V1\FieldBoost\Interval\Extension instead.
     * @deprecated
     */
    class FieldBoost_Interval_Extension {}
}
class_exists(FieldBoost\Interval\Extension::class);
@trigger_error('Sajari\Engine\Query\V1\FieldBoost_Interval_Extension is deprecated and will be removed in the next major release. Use Sajari\Engine\Query\V1\FieldBoost\Interval\Extension instead', E_USER_DEPRECATED);

