<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/engine/query/v1/query.proto

namespace Sajari\Engine\Query\V1;

if (false) {
    /**
     * This class is deprecated. Use Sajari\Engine\Query\V1\FieldBoost\Text instead.
     * @deprecated
     */
    class FieldBoost_Text {}
}
class_exists(FieldBoost\Text::class);
@trigger_error('Sajari\Engine\Query\V1\FieldBoost_Text is deprecated and will be removed in the next major release. Use Sajari\Engine\Query\V1\FieldBoost\Text instead', E_USER_DEPRECATED);

