<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/engine/query/v1/query.proto

namespace Sajari\Engine\Query\V1;

if (false) {
    /**
     * This class is deprecated. Use Sajari\Engine\Query\V1\Filter\Field\Operator instead.
     * @deprecated
     */
    class Filter_Field_Operator {}
}
class_exists(Filter\Field\Operator::class);
@trigger_error('Sajari\Engine\Query\V1\Filter_Field_Operator is deprecated and will be removed in the next major release. Use Sajari\Engine\Query\V1\Filter\Field\Operator instead', E_USER_DEPRECATED);

