<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/engine/query/v1/query.proto

namespace Sajari\Engine\Query\V1;

/**
 * <pre>
 * Operator is an enumeration of combination operators.
 * </pre>
 *
 * Protobuf enum <code>sajari.engine.query.v1.Filter.Combinator.Operator</code>
 */
class Filter_Combinator_Operator
{
    /**
     * <pre>
     * All of the filters must be satisfied.
     * </pre>
     *
     * <code>ALL = 0;</code>
     */
    const ALL = 0;
    /**
     * <pre>
     * Any of the filters must be satisfied.
     * </pre>
     *
     * <code>ANY = 1;</code>
     */
    const ANY = 1;
    /**
     * <pre>
     * One of the filters (and only one) must be satisfied.
     * </pre>
     *
     * <code>ONE = 2;</code>
     */
    const ONE = 2;
    /**
     * <pre>
     * None of the filters must be satisfied.
     * </pre>
     *
     * <code>NONE = 3;</code>
     */
    const NONE = 3;
}

