<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/engine/query/v1/query.proto

namespace Sajari\Engine\Query\V1;

if (false) {
    /**
     * This class is deprecated. Use Sajari\Engine\Query\V1\SearchRequest\FeatureQuery instead.
     * @deprecated
     */
    class SearchRequest_FeatureQuery {}
}
class_exists(SearchRequest\FeatureQuery::class);
@trigger_error('Sajari\Engine\Query\V1\SearchRequest_FeatureQuery is deprecated and will be removed in the next major release. Use Sajari\Engine\Query\V1\SearchRequest\FeatureQuery instead', E_USER_DEPRECATED);

