<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/engine/query/v1/query.proto

namespace Sajari\Engine\Query\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Term represents a tokenized piece of text (i.e. a single word, or number).
 *
 * Generated from protobuf message <code>sajari.engine.query.v1.Term</code>
 */
class Term extends \Google\Protobuf\Internal\Message
{
    /**
     * Term string value.
     *
     * Generated from protobuf field <code>string value = 1;</code>
     */
    private $value = '';
    /**
     * Field that the term originated from.
     *
     * Generated from protobuf field <code>string field = 2;</code>
     */
    private $field = '';
    /**
     * Number of positive interactions (uint16) this Term instance has been involved with.
     *
     * Generated from protobuf field <code>uint32 pos = 3;</code>
     */
    private $pos = 0;
    /**
     * Number of negative interactions (uint16) this Term instance has been involved with.
     *
     * Generated from protobuf field <code>uint32 neg = 4;</code>
     */
    private $neg = 0;
    /**
     * Significance of the term (uint16).
     *
     * Generated from protobuf field <code>double weight = 5;</code>
     */
    private $weight = 0.0;
    /**
     * Word offset (context) (uint16).
     * The position of this term instance in it's immediate context (i.e. paragraph).
     *
     * Generated from protobuf field <code>uint32 word_offset = 6;</code>
     */
    private $word_offset = 0;
    /**
     * Paragraph offset (context) (uint16).
     * The paragraph position (a grouping of term instances) in a body string.
     *
     * Generated from protobuf field <code>uint32 para_offset = 7;</code>
     */
    private $para_offset = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $value
     *           Term string value.
     *     @type string $field
     *           Field that the term originated from.
     *     @type int $pos
     *           Number of positive interactions (uint16) this Term instance has been involved with.
     *     @type int $neg
     *           Number of negative interactions (uint16) this Term instance has been involved with.
     *     @type float $weight
     *           Significance of the term (uint16).
     *     @type int $word_offset
     *           Word offset (context) (uint16).
     *           The position of this term instance in it's immediate context (i.e. paragraph).
     *     @type int $para_offset
     *           Paragraph offset (context) (uint16).
     *           The paragraph position (a grouping of term instances) in a body string.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Sajari\Engine\Query\V1\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Term string value.
     *
     * Generated from protobuf field <code>string value = 1;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Term string value.
     *
     * Generated from protobuf field <code>string value = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

    /**
     * Field that the term originated from.
     *
     * Generated from protobuf field <code>string field = 2;</code>
     * @return string
     */
    public function getField()
    {
        return $this->field;
    }

    /**
     * Field that the term originated from.
     *
     * Generated from protobuf field <code>string field = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setField($var)
    {
        GPBUtil::checkString($var, True);
        $this->field = $var;

        return $this;
    }

    /**
     * Number of positive interactions (uint16) this Term instance has been involved with.
     *
     * Generated from protobuf field <code>uint32 pos = 3;</code>
     * @return int
     */
    public function getPos()
    {
        return $this->pos;
    }

    /**
     * Number of positive interactions (uint16) this Term instance has been involved with.
     *
     * Generated from protobuf field <code>uint32 pos = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPos($var)
    {
        GPBUtil::checkUint32($var);
        $this->pos = $var;

        return $this;
    }

    /**
     * Number of negative interactions (uint16) this Term instance has been involved with.
     *
     * Generated from protobuf field <code>uint32 neg = 4;</code>
     * @return int
     */
    public function getNeg()
    {
        return $this->neg;
    }

    /**
     * Number of negative interactions (uint16) this Term instance has been involved with.
     *
     * Generated from protobuf field <code>uint32 neg = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setNeg($var)
    {
        GPBUtil::checkUint32($var);
        $this->neg = $var;

        return $this;
    }

    /**
     * Significance of the term (uint16).
     *
     * Generated from protobuf field <code>double weight = 5;</code>
     * @return float
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Significance of the term (uint16).
     *
     * Generated from protobuf field <code>double weight = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkDouble($var);
        $this->weight = $var;

        return $this;
    }

    /**
     * Word offset (context) (uint16).
     * The position of this term instance in it's immediate context (i.e. paragraph).
     *
     * Generated from protobuf field <code>uint32 word_offset = 6;</code>
     * @return int
     */
    public function getWordOffset()
    {
        return $this->word_offset;
    }

    /**
     * Word offset (context) (uint16).
     * The position of this term instance in it's immediate context (i.e. paragraph).
     *
     * Generated from protobuf field <code>uint32 word_offset = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setWordOffset($var)
    {
        GPBUtil::checkUint32($var);
        $this->word_offset = $var;

        return $this;
    }

    /**
     * Paragraph offset (context) (uint16).
     * The paragraph position (a grouping of term instances) in a body string.
     *
     * Generated from protobuf field <code>uint32 para_offset = 7;</code>
     * @return int
     */
    public function getParaOffset()
    {
        return $this->para_offset;
    }

    /**
     * Paragraph offset (context) (uint16).
     * The paragraph position (a grouping of term instances) in a body string.
     *
     * Generated from protobuf field <code>uint32 para_offset = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setParaOffset($var)
    {
        GPBUtil::checkUint32($var);
        $this->para_offset = $var;

        return $this;
    }

}

