<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/engine/query/v1/query.proto

namespace Sajari\Engine\Query\V1\Aggregate\Bucket;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Bucket represents records which satisfy a Filter.
 *
 * Generated from protobuf message <code>sajari.engine.query.v1.Aggregate.Bucket.Bucket</code>
 */
class Bucket extends \Google\Protobuf\Internal\Message
{
    /**
     * Name of the bucket.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * Filter satisfied by records in the bucket.
     *
     * Generated from protobuf field <code>.sajari.engine.query.v1.Filter filter = 2;</code>
     */
    private $filter = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Name of the bucket.
     *     @type \Sajari\Engine\Query\V1\Filter $filter
     *           Filter satisfied by records in the bucket.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Sajari\Engine\Query\V1\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Name of the bucket.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Name of the bucket.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Filter satisfied by records in the bucket.
     *
     * Generated from protobuf field <code>.sajari.engine.query.v1.Filter filter = 2;</code>
     * @return \Sajari\Engine\Query\V1\Filter
     */
    public function getFilter()
    {
        return $this->filter;
    }

    /**
     * Filter satisfied by records in the bucket.
     *
     * Generated from protobuf field <code>.sajari.engine.query.v1.Filter filter = 2;</code>
     * @param \Sajari\Engine\Query\V1\Filter $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkMessage($var, \Sajari\Engine\Query\V1\Filter::class);
        $this->filter = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Bucket::class, \Sajari\Engine\Query\V1\Aggregate_Bucket_Bucket::class);

