<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/engine/store/record/record.proto

namespace Sajari\Engine\Store\Record\MutateRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sajari.engine.store.record.MutateRequest.RecordMutation</code>
 */
class RecordMutation extends \Google\Protobuf\Internal\Message
{
    /**
     * Key which uniquely identifies record.
     *
     * Generated from protobuf field <code>.sajari.engine.Key key = 1;</code>
     */
    private $key = null;
    /**
     * List of fields to mutate.
     *
     * Generated from protobuf field <code>repeated .sajari.engine.store.record.MutateRequest.RecordMutation.FieldMutation field_mutations = 2;</code>
     */
    private $field_mutations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Sajari\Engine\Key $key
     *           Key which uniquely identifies record.
     *     @type \Sajari\Engine\Store\Record\MutateRequest\RecordMutation\FieldMutation[]|\Google\Protobuf\Internal\RepeatedField $field_mutations
     *           List of fields to mutate.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Sajari\Engine\Store\Record\Record::initOnce();
        parent::__construct($data);
    }

    /**
     * Key which uniquely identifies record.
     *
     * Generated from protobuf field <code>.sajari.engine.Key key = 1;</code>
     * @return \Sajari\Engine\Key
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Key which uniquely identifies record.
     *
     * Generated from protobuf field <code>.sajari.engine.Key key = 1;</code>
     * @param \Sajari\Engine\Key $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkMessage($var, \Sajari\Engine\Key::class);
        $this->key = $var;

        return $this;
    }

    /**
     * List of fields to mutate.
     *
     * Generated from protobuf field <code>repeated .sajari.engine.store.record.MutateRequest.RecordMutation.FieldMutation field_mutations = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFieldMutations()
    {
        return $this->field_mutations;
    }

    /**
     * List of fields to mutate.
     *
     * Generated from protobuf field <code>repeated .sajari.engine.store.record.MutateRequest.RecordMutation.FieldMutation field_mutations = 2;</code>
     * @param \Sajari\Engine\Store\Record\MutateRequest\RecordMutation\FieldMutation[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFieldMutations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sajari\Engine\Store\Record\MutateRequest\RecordMutation\FieldMutation::class);
        $this->field_mutations = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(RecordMutation::class, \Sajari\Engine\Store\Record\MutateRequest_RecordMutation::class);

