<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/engine/store/record/record.proto

namespace Sajari\Engine\Store\Record;

if (false) {
    /**
     * This class is deprecated. Use Sajari\Engine\Store\Record\MutateRequest\RecordMutation instead.
     * @deprecated
     */
    class MutateRequest_RecordMutation {}
}
class_exists(MutateRequest\RecordMutation::class);
@trigger_error('Sajari\Engine\Store\Record\MutateRequest_RecordMutation is deprecated and will be removed in the next major release. Use Sajari\Engine\Store\Record\MutateRequest\RecordMutation instead', E_USER_DEPRECATED);

