<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/engine/store/record/record.proto

namespace Sajari\Engine\Store\Record;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Record is a single record made up of key-value pairs.
 * </pre>
 *
 * Protobuf type <code>sajari.engine.store.record.Record</code>
 */
class Record extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * A map of key-value pairs.
     * </pre>
     *
     * <code>map&lt;string, .sajari.engine.Value&gt; values = 1;</code>
     */
    private $values;

    public function __construct() {
        \GPBMetadata\Sajari\Engine\Store\Record\Record::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * A map of key-value pairs.
     * </pre>
     *
     * <code>map&lt;string, .sajari.engine.Value&gt; values = 1;</code>
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * <pre>
     * A map of key-value pairs.
     * </pre>
     *
     * <code>map&lt;string, .sajari.engine.Value&gt; values = 1;</code>
     */
    public function setValues(&$var)
    {
        $this->values = $var;
    }

}

