<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/api/query/v1/query.proto

namespace Sajari\Api\Query\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * SearchResponse is a wrapped response from the engine with interaction tokens
 * and other information which was used to construct the query from the SearchRequest.
 *
 * Generated from protobuf message <code>sajari.api.query.v1.SearchResponse</code>
 */
class SearchResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * SearchResponse from the engine request.
     *
     * Generated from protobuf field <code>.sajari.engine.query.v1.SearchResponse search_response = 1;</code>
     */
    private $search_response = null;
    /**
     * SearchRequest used in the query (if this has been changed).
     *
     * Generated from protobuf field <code>.sajari.engine.query.v1.SearchRequest search_request = 2;</code>
     */
    private $search_request = null;
    /**
     * Tokens which correspond to the result records.
     *
     * Generated from protobuf field <code>repeated .sajari.api.query.v1.Token tokens = 3;</code>
     */
    private $tokens;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Sajari\Engine\Query\V1\SearchResponse $search_response
     *           SearchResponse from the engine request.
     *     @type \Sajari\Engine\Query\V1\SearchRequest $search_request
     *           SearchRequest used in the query (if this has been changed).
     *     @type \Sajari\Api\Query\V1\Token[]|\Google\Protobuf\Internal\RepeatedField $tokens
     *           Tokens which correspond to the result records.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Sajari\Api\Query\V1\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * SearchResponse from the engine request.
     *
     * Generated from protobuf field <code>.sajari.engine.query.v1.SearchResponse search_response = 1;</code>
     * @return \Sajari\Engine\Query\V1\SearchResponse
     */
    public function getSearchResponse()
    {
        return $this->search_response;
    }

    /**
     * SearchResponse from the engine request.
     *
     * Generated from protobuf field <code>.sajari.engine.query.v1.SearchResponse search_response = 1;</code>
     * @param \Sajari\Engine\Query\V1\SearchResponse $var
     * @return $this
     */
    public function setSearchResponse($var)
    {
        GPBUtil::checkMessage($var, \Sajari\Engine\Query\V1\SearchResponse::class);
        $this->search_response = $var;

        return $this;
    }

    /**
     * SearchRequest used in the query (if this has been changed).
     *
     * Generated from protobuf field <code>.sajari.engine.query.v1.SearchRequest search_request = 2;</code>
     * @return \Sajari\Engine\Query\V1\SearchRequest
     */
    public function getSearchRequest()
    {
        return $this->search_request;
    }

    /**
     * SearchRequest used in the query (if this has been changed).
     *
     * Generated from protobuf field <code>.sajari.engine.query.v1.SearchRequest search_request = 2;</code>
     * @param \Sajari\Engine\Query\V1\SearchRequest $var
     * @return $this
     */
    public function setSearchRequest($var)
    {
        GPBUtil::checkMessage($var, \Sajari\Engine\Query\V1\SearchRequest::class);
        $this->search_request = $var;

        return $this;
    }

    /**
     * Tokens which correspond to the result records.
     *
     * Generated from protobuf field <code>repeated .sajari.api.query.v1.Token tokens = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTokens()
    {
        return $this->tokens;
    }

    /**
     * Tokens which correspond to the result records.
     *
     * Generated from protobuf field <code>repeated .sajari.api.query.v1.Token tokens = 3;</code>
     * @param \Sajari\Api\Query\V1\Token[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTokens($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sajari\Api\Query\V1\Token::class);
        $this->tokens = $arr;

        return $this;
    }

}

