<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/api/query/v1/query.proto

namespace Sajari\Api\Query\V1;

/**
 * Protobuf enum <code>sajari.api.query.v1.Transform.RunType</code>
 */
class Transform_RunType
{
    /**
     * <pre>
     * Run the transform before the query.
     * </pre>
     *
     * <code>PRE_QUERY = 0;</code>
     */
    const PRE_QUERY = 0;
    /**
     * <pre>
     * Run the transform on the request.
     * </pre>
     *
     * <code>POST_NON_EMPTY = 1;</code>
     */
    const POST_NON_EMPTY = 1;
    /**
     * <pre>
     * After an empty query this will apply the transform to the query and the re-run the query.
     * </pre>
     *
     * <code>POST_EMPTY_PRE_RETRY = 2;</code>
     */
    const POST_EMPTY_PRE_RETRY = 2;
}

