<?php
/**
 * TextPositionTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Sajari
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Search.io API
 *
 * Search.io offers a search and discovery service with Neuralsearch®, the world's first instant AI search technology. Businesses of all sizes use Search.io to build site search and discovery solutions that maximize e-commerce revenue, optimize on-site customer experience, and scale their online presence.
 *
 * The version of the OpenAPI document: v4
 * Contact: support@search.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Sajari\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * TextPositionTest Class Doc Comment
 *
 * @category    Class
 * @description TextPosition describes the position of text in a box.   - TEXT_POSITION_UNSPECIFIED: No position specified.  - TEXT_POSITION_CENTER: The text is positioned in the horizontal and vertical center.  - TEXT_POSITION_TOP_LEFT: The text is positioned in the top left corner.  - TEXT_POSITION_TOP_RIGHT: The text is positioned in the top right corner.  - TEXT_POSITION_BOTTOM_LEFT: The text is positioned in the bottom left corner.  - TEXT_POSITION_BOTTOM_RIGHT: The text is positioned in the bottom right corner.
 * @package     Sajari
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TextPositionTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TextPosition"
     */
    public function testTextPosition()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }
}
