<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sajari/engine/store/term/term.proto

namespace Sajari\Engine\Store\Term;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Information for a list of terms.
 * </pre>
 *
 * Protobuf type <code>sajari.engine.store.term.Infos</code>
 */
class Infos extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Information for a list of terms.
     * </pre>
     *
     * <code>repeated .sajari.engine.store.term.Infos.Info infos = 1;</code>
     */
    private $infos;

    public function __construct() {
        \GPBMetadata\Sajari\Engine\Store\Term\Term::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Information for a list of terms.
     * </pre>
     *
     * <code>repeated .sajari.engine.store.term.Infos.Info infos = 1;</code>
     */
    public function getInfos()
    {
        return $this->infos;
    }

    /**
     * <pre>
     * Information for a list of terms.
     * </pre>
     *
     * <code>repeated .sajari.engine.store.term.Infos.Info infos = 1;</code>
     */
    public function setInfos(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sajari\Engine\Store\Term\Infos_Info::class);
        $this->infos = $var;
    }

}

